pluginManagement {
    includeBuild('gradle/build-logic')
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven { url = 'https://maven.parchmentmc.org' }
    }
}

rootProject.name = 'nclskins'

include 'client-contract'
include 'client-runtime'
include 'core'
include 'server-contract'
include 'server-runtime'
include 'server-vanilla-publication'
