plugins {
    id 'java-library'
}

def packaging = rootProject.extensions.extraProperties
        .get('nclskinsTargetCatalog').serverPlugin.packaging

repositories {
    maven { url = 'https://oss.sonatype.org/content/repositories/snapshots/' }
    maven { url = 'https://libraries.minecraft.net/' }
}

dependencies {
    api project(':server-plugin-common')
    compileOnly "net.md-5:bungeecord-api:${packaging.bungeeApi}"

    testImplementation platform('org.junit:junit-bom:5.11.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
