plugins {
    id 'java-library'
}

dependencies {
    compileOnly 'org.slf4j:slf4j-api:2.0.1'

    testImplementation platform('org.junit:junit-bom:5.11.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.slf4j:slf4j-api:2.0.1'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
